package chylex.hee.entity.fx.handler;

public enum FXType{
	ESSENCE_ALTAR_SMOKE,
	LASER_BEAM_DESTROY,
	SPOOKY_LOG_DECAY,
	SPOOKY_LEAVES_DECAY,
	GEM_LINK,
	GEM_TELEPORT_TO,
	ENDER_PEARL_FREEZE,
	IGNEOUS_ROCK_MELT,
	ENDERMAN_BLOODLUST_TRANSFORMATION,
	ENDER_GUARDIAN_TELEPORT;
	
	public static FXType[] values = values();
}
